fallback_user:
email_subdomain:

uv_api_key:
uv_api_secret:
uv_subdomain:

aha_api_key:
aha_subdomain:
aha_idea_portal_id:
aha_product_id:
aha_sf_integration_id:

aha_default_status: New
aha_default_category:

category_map:
  "UV Category Name": "Aha Category Name"
status_map:
  "UV Status": "Aha Status"

sf_subdomain:
sf_access_token: